/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.twofortyfouram.locale.api;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static int twofortyfouram_locale_ic_menu_dontsave=0x7f020000;
        public static int twofortyfouram_locale_ic_menu_help=0x7f020001;
        public static int twofortyfouram_locale_ic_menu_save=0x7f020002;
    }
    public static final class id {
        /**  Menu item to cancel the current Activity 
         */
        public static int twofortyfouram_locale_menu_dontsave=0x7f030001;
        /**  Menu item to launch the Help 
         */
        public static int twofortyfouram_locale_menu_help=0x7f030000;
        /**  Menu item to save the current Activity 
         */
        public static int twofortyfouram_locale_menu_save=0x7f030002;
    }
    public static final class integer {
        /**  The maximum blurb length in characters.  This value is based on Latin characters. 
         */
        public static int twofortyfouram_locale_maximum_blurb_length=0x7f040000;
    }
    public static final class menu {
        public static int twofortyfouram_locale_help_save_dontsave=0x7f070000;
    }
    public static final class string {
        /**  A format string for breadcrumbs in the titlebar.  For left to right languages, such as English, the format will look something like "Main Activity > Sub Activity > Sub Activity 2".  Item #1 is the previous path, item #2 is the separator, and item #3 is the current item.  For most left to right languages, this shouldn't need to be changed. 
         */
        public static int twofortyfouram_locale_breadcrumb_format=0x7f050000;
        /**  The separator character for breadcrumbs.  For most left to right languages, this shouldn't need to be changed. 
         */
        public static int twofortyfouram_locale_breadcrumb_separator=0x7f050001;
        /**  The Don't Save button in the menu or Action Bar.  MDPI 21 character maximum 
         */
        public static int twofortyfouram_locale_menu_dontsave=0x7f050002;
        /**  The Help button in the menu or Action Bar.  MDPI 21 character maximum 
         */
        public static int twofortyfouram_locale_menu_help=0x7f050003;
        /**  The Save button in the menu or Action Bar.  MDPI 21 character maximum 
         */
        public static int twofortyfouram_locale_menu_save=0x7f050004;
    }
    public static final class style {
        /**  Stupid Motorola.  This is a hack to avoid hideous ListViews on Motoblur devices.  http://community.developer.motorola.com/t5/MOTODEV-Blog/Why-Does-My-ListView-Look-Different/ba-p/17462 
         */
        public static int MotorolaListViewHackStyle=0x7f060003;
        /**  Dark style for all standard Locale and Locale plug-in Activity instances 
         */
        public static int Theme_Locale_Dark=0x7f060000;
        /**  Style for Activities that look like a dialog 
         */
        public static int Theme_Locale_Dialog=0x7f060002;
        /**  Light style for use within Locale.  This theme is usually not used.  The only place Locale uses this theme is to make dialogs look correct on Android 2.3 and earlier, because http://developer.android.com/reference/android/app/AlertDialog.Builder.html#getContext() requires Android 3.0. 
         */
        public static int Theme_Locale_Light=0x7f060001;
    }
}
